<?php

/**
 * Test class for Application_Model_SuperDuperMapper.
 * Generated by PHPUnit on 2012-09-09 at 13:58:10.
 */
class Application_Model_RouteStopTimeMapperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application_Model_SuperDuperMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application_Model_RouteStopTimeMapper;
    }

    public function testGetTimes() {

        $routeShortName = "K";
        $stopName = "Arrott Transportation Center";
        $serviceId = GMH_Septa_ServiceId::$WEEKDAY;
        $directionId = "0";
        $from = "4:50 PM";
        $to   = "5:30 PM";
        
        $route = $this->object->fetchStopTimes(
                $routeShortName,  $serviceId, $stopName, $directionId,$from,$to
        );

        $this->assertEquals( 4, $route->getTrips );
    }

}

?>
