<?php

/**
 * Test class for Application_Model_SuperDuperMapper.
 * Generated by PHPUnit on 2012-09-09 at 13:58:10.
 */
class Application_Model_SuperDuperMapperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application_Model_SuperDuperMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Application_Model_SuperDuperMapper;
    }

    public function testGetTimes() {
        $minutesFromNow = 60;
        
        // k bus
        $routeId = "10726";
        $stopId = "220";
        
        $nowTime = date('H:i:s', time() );
        $thenTime = date('H:i:s', time() + $minutesFromNow * 60 );
        
        $stopTimes =  $this->object->fetchStopTimes( 
                $routeId, 
                $stopId, 
                $service_id = GMH_ServiceId::$WEEKDAY,
                $direction_id="0",
                $nowTime, 
                $thenTime
            );
        
        Zend_Debug::dump( $stopTimes );
        
        $this->assertEquals( 4, count( $stopTimes ) );
    }

}

?>
