<?php
$this->addHelperPath(APPLICATION_PATH . '/views/helpers', 'Application_View_Helper_');
$this->headTitle( "Get Me Home" );

$stopName = $this->response->getStopName();
$directionId = $this->response->getDirectionId();
?> 

    <div class="row">
        
        <span>From:</span>
        
        <span>
            <?=$this->timeViewHelper( $this->response->getFromTime() )?>
        </span>
        
    </div>

    <div>
        
        <div>&nbsp;</div> 
        
        <?php foreach( $this->response->getStopTimes() as $stopTime ) : ?>
        
           <div class="row">
               <?php echo $this->timeViewHelper($stopTime->getDepartureTime() ); ?>
               &nbsp;-&nbsp;
               <?php foreach( $this->response->getRoutesByStopTime( $stopTime->getDepartureTime() )  as $route ) : ?>
                    <span><?=$route->getRouteShortName()?></span>
               <?php endforeach; ?>
           </div>
        <?php endforeach; ?>
        
    </div>
