 <?php
$this->headLink()->appendStylesheet("/css/skeleton/base.css");
$this->headLink()->appendStylesheet("/css/skeleton/layout.css");
$this->headLink()->appendStylesheet("/css/skeleton/skeleton.css");
 
$this->headLink()->appendStylesheet("/css/style.css");
$this->headLink()->appendStylesheet("/css/debug.css");
 
?>
 <html> 

    <head> 
        <?php echo $this->headTitle()."\n"; ?>
        <?php echo $this->headLink()."\n"; ?>
        <?php echo $this->headScript()."\n"; ?>
    </head> 
    
    <body>
        
        <div class="container">
            <div class="ten columns greyskie offset-by-six">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
    
 </html>