 <html> 

<head> 

  <meta name=viewport content="user-scalable=no,width=600px" />

  <link rel=stylesheet

        href=http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.css />

  <script src=http://code.jquery.com/jquery-1.6.min.js></script>

  <script src=http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.min.js>

  </script>
<link rel=stylesheet

        href="/css/style.css" />
</head> 
<body>
<?php echo $this->layout()->content; ?>
</body>
 </html>