<?php

require_once dirname(__FILE__) . '/../../scripts/initSeptaDb.php';

/**
 * Test class for InitSeptaDb.
 * Generated by PHPUnit on 2012-08-29 at 05:57:17.
 */
class InitSeptaDbTest extends PHPUnit_Framework_TestCase {

    /**
     * @var InitSeptaDb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InitSeptaDb();
    }
    
    public function testGetFileNames() {
        
        $files = $this->object->getFileNames( 
                getenv('APPLICATION_PATH') . "../scripts/google_bus" );
        
        $this->assertEquals( "../scripts/google_bus/agency.txt", $files[0] );
        $this->assertEquals( 11, count( $files ) );
    }
}

?>
